### PR TITLE
Add 'help wanted' to the list of excluded labels

### PR DESCRIPTION
**Pull request by limonte**
`help wanted` is the default label for GitHub repositories:

I think that issues with `help wanted` label should be excluded from the median issue resolution time calculation.

### CODE REVIEW

**Comment by mnapoli** [comment]
Hi, thanks for the pull request. I'm not sure I see why those issues should be excluded for the calculations? They could still be bugs

**Comment by limonte** [comment]
You're totally right, an issue labelled `help wanted` could be a bug. As well as `wip` labelled could be a bug and `wip` is in the list of excluded labels for the calculation.

Often project owner or collaborators submit issues by theirseft and label those issues with `help wanted`. For example, my OS project has two of such issues: https://github.com/limonte/sweetalert2/issues/364 and https://github.com/limonte/sweetalert2/issues/388

IMO it's better to exclude such issues from calculation.

PS. Totally forgot to say THANK YOU for the awesome idea and great implementation!

**Comment by mnapoli** [comment]
Thanks :)

`wip` is often used for pull requests that are in progress, so if such PR is 2 month old it's not the "fault" of the package maintainer for not merging it.

`help wanted` is a bit more fuzzy to me, that a maintainer needs help or not to fix a bug, the bug is still not fixed. Does that make sense for you?

**Comment by limonte** [comment]
Yeah, makes sense, I'll close this PR :+1: 

Anyway, thanks again! I'm using the IsItMaintained badge on my project [SweetAlert2](https://github.com/limonte/sweetalert2) which is trending JS repository now :rocket:

**Comment by mnapoli** [comment]
Nice!

**Pull request closed without merging**
