### PR TITLE
Upgrade to Stratify 0.3

### PR DESCRIPTION
**Pull request by mnapoli**

### CODE REVIEW

**Comment by Clashsoft** [comment]
How is one supposed to report problems when the issue tracker is disabled?

**Comment by mnapoli** [comment]
@Clashsoft on this project specifically I don't take requests nor do I have a TODO list. If you want something, you may send a pull request.

**Comment by Clashsoft** [comment]
I don't think that is a good policy. Just because I found a bug does not mean I have the means or insight to make a fix. If you don't have the time to work on the project any more, that's fine. But you should still allow people to submit their issues. Maybe someone else has fun in solving them.

**Comment by mnapoli** [comment]
I understand. I am not actively maintaining this project at the moment (it works for me and I'm happy with the current situation), I might change that later.

**Review by Bdrake317 — APPROVED** [review]

**Pull request closed without merging**
